[custom]

;设置规则标志位
ruleset=!!import:https://raw.githubusercontent.com/KervynH/clash-config/refs/heads/main/snippets/rulesets-mini.list
;设置规则标志位

;设置分组标志位
;;;手动分组
custom_proxy_group=!!import:https://raw.githubusercontent.com/KervynH/clash-config/refs/heads/main/snippets/groups-core-front.list
custom_proxy_group=!!🤖 AI服务`select`[]🚀 节点选择`[]☑️ 手动切换`[]🎯 全球直连
custom_proxy_group=!!import:https://raw.githubusercontent.com/KervynH/clash-config/refs/heads/main/snippets/groups-core-final.list
custom_proxy_group=!!import:https://raw.githubusercontent.com/KervynH/clash-config/refs/heads/main/snippets/groups-passive-auto.list
;设置分组标志位

;自定义emoji标志位
add_emoji=true
remove_old_emoji=true
;;; 导入自定义 emoji
emoji=!!import:https://raw.githubusercontent.com/KervynH/clash-config/refs/heads/main/snippets/emoji-custom.list
;;; 导入后端 emoji 做兜底
emoji=!!import:snippets/emoji.txt
;自定义emoji标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
